/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedCard: typeof import('./src/components/AdvancedCard.vue')['default']
    Copyright: typeof import('./src/components/layouts/Footer/Copyright.vue')['default']
    FAQSection: typeof import('./src/components/layouts/FAQSection.vue')['default']
    FeaturedRecipe: typeof import('./src/components/recipes/FeaturedRecipe.vue')['default']
    FeaturedRecipeSkeleton: typeof import('./src/components/recipes/FeaturedRecipeSkeleton.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    Nav: typeof import('./src/components/layouts/Nav.vue')['default']
    NavLinks: typeof import('./src/components/layouts/Footer/NavLinks.vue')['default']
    NewsletterAndFAQSection: typeof import('./src/components/sections/NewsletterAndFAQSection.vue')['default']
    NewsletterSection: typeof import('./src/components/layouts/NewsletterSection.vue')['default']
    RecipeCard: typeof import('./src/components/recipes/RecipeCard.vue')['default']
    RecipeCardSkeleton: typeof import('./src/components/recipes/RecipeCardSkeleton.vue')['default']
    RecipeGridSection: typeof import('./src/components/sections/RecipeGridSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLinks: typeof import('./src/components/layouts/Footer/SocialLinks.vue')['default']
  }
}
